// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSJr4Jl-fsr5TYIJwzGfCtzsRMmqOpsIA',
    appId: '1:747822439007:web:c590b0616ba70bc36259ea',
    messagingSenderId: '747822439007',
    projectId: 'food-delivery-bf8ae',
    authDomain: 'food-delivery-bf8ae.firebaseapp.com',
    storageBucket: 'food-delivery-bf8ae.firebasestorage.app',
    measurementId: 'G-PBFDKT303F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBM0IzBf8WnIDCwNGNv0XKMTEV_6OF4Vc',
    appId: '1:747822439007:android:5d1e6c2506583da66259ea',
    messagingSenderId: '747822439007',
    projectId: 'food-delivery-bf8ae',
    storageBucket: 'food-delivery-bf8ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvr1oT2OMTMaM993ODGP2n0abT-KH6vyM',
    appId: '1:747822439007:ios:8adaeac923e55d096259ea',
    messagingSenderId: '747822439007',
    projectId: 'food-delivery-bf8ae',
    storageBucket: 'food-delivery-bf8ae.firebasestorage.app',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSJr4Jl-fsr5TYIJwzGfCtzsRMmqOpsIA',
    appId: '1:747822439007:web:49d595887e2cae6f6259ea',
    messagingSenderId: '747822439007',
    projectId: 'food-delivery-bf8ae',
    authDomain: 'food-delivery-bf8ae.firebaseapp.com',
    storageBucket: 'food-delivery-bf8ae.firebasestorage.app',
    measurementId: 'G-RTXZ2XCDKJ',
  );
}
